# Generated by Django 5.1.4 on 2024-12-25 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccreditationApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_category', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('ogrn', models.CharField(max_length=13, unique=True)),
                ('inn', models.CharField(max_length=12, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('representative_category', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('representative_phone_number', models.CharField(max_length=15)),
                ('representative_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('document_type', models.CharField(max_length=255)),
                ('document_series', models.CharField(max_length=10)),
                ('document_number', models.CharField(max_length=15)),
                ('document_date', models.DateField()),
                ('issued_by', models.TextField()),
                ('subdivision_code', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
