# Generated by Django 5.1.4 on 2024-12-26 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accreditationapplication',
            name='status',
            field=models.CharField(choices=[('not_reviewed', 'Не рассмотрено'), ('invalid_docs', 'Неправильные документы'), ('rejected', 'Отказано в аккредитации'), ('approved', 'Аккредитовано')], default='not_reviewed', max_length=20),
        ),
    ]
